### ISSUE TITLE
Modrinth wrong version listing

### ISSUE THREAD

**Issue by sternschnaube** [IMB11/SnowUnderTrees#9]
Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1002) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.class_3193 does not have member field 'com.mojang.datafixers.util.Either field_16427'
	at dev.imb11.snowundertrees.world.WorldTickHandler.processChunk(WorldTickHandler.java:40) ~[SnowUnderTrees-2.3.0+1.20.2.jar:?]
	at dev.imb11.snowundertrees.world.WorldTickHandler.lambda$onStartTick$0(WorldTickHandler.java:35) ~[SnowUnderTrees-2.3.0+1.20.2.jar:?]
	at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1719) ~[fastutil-8.5.12.jar:?]
	at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:110) ~[guava-32.1.2-jre.jar:?]
	at dev.imb11.snowundertrees.world.WorldTickHandler.onStartTick(WorldTickHandler.java:35) ~[SnowUnderTrees-2.3.0+1.20.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$4(ServerTickEvents.java:52) ~[fabric-lifecycle-events-v1-2.3.4+c5fc38b3ff-6c2fd8f8a2756310.jar:?]
	at net.minecraft.class_3218.handler$eai000$fabric-lifecycle-events-v1$startWorldTick(class_3218.java:18298) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:304) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$379(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.wrapOperation$bcp000$carpet-ams-addition$tickWorlds(MinecraftServer.java:5075) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$wrapOperation$bcp000$carpet-ams-addition$tickWorlds$380(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.wrapOperation$dde000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:8577) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998) ~[server-intermediary.jar:?]
	... 5 more

**Comment by ItsRodrigoAl** [comment]
He made a mistake selecting the correct versions for the releases. He marked the 1.20.2 versions as an 1.20.6 version, which is not. You just need to download the correct versions, which is the third one, not the first one

**Comment by sternschnaube** [comment]
Thanks! I was already wondering about the file name.

**Comment by IMB11** [comment]
Fixed, whoops lol. I do this every time haha 🤣
